title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://vincentivarsson.github.io/FAQ-Byggdialog/

aux_links:
  Template Repository: https://github.com/Vincentivarsson/FAQ-Byggdialog
